import { ComponentFixture, TestBed } from '@angular/core/testing';

import { AutogeneratedReportComponent } from './autogenerated-report.component';

describe('AutogeneratedReportComponent', () => {
  let component: AutogeneratedReportComponent;
  let fixture: ComponentFixture<AutogeneratedReportComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AutogeneratedReportComponent]
    })
    .compileComponents();

    fixture = TestBed.createComponent(AutogeneratedReportComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
