import { Component } from '@angular/core';
import { ReportService } from '../../services/report.service';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { Report } from '../../../models/report.model';


@Component({
  selector: 'app-autogenerated-report',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './autogenerated-report.component.html',
  styleUrls: ['./autogenerated-report.component.scss']
})
export class AutogeneratedReportComponent {
  report: any;

  constructor(private reportService: ReportService, private router: Router) {}

  ngOnInit(): void {
    this.report = this.reportService.generateReport();
  }

 
  onSubmitReport(): void {
    const userId = Number(localStorage.getItem('userId')); 
    const reportDataString = JSON.stringify(this.report); 
    const type = localStorage.getItem('userRole') ?? '';
    
    const newReport= new Report(
      type,                
      reportDataString,    
      userId,              
         
    );

    console.log("report",reportDataString);
    this.reportService.createReport(newReport).subscribe(
      () => {
        alert('Report added successfully!');
        this.reportService.clearStorage();
        this.onClose();
      },
      (error) => {
        console.error('Error adding report', error);
        alert('Failed to add report.');
      }
    );
  }

  onClose(){
    
      const role=localStorage.getItem("userRole");
      switch (role) {
        case 'Admin':
          this.router.navigate(['/main/dashboard']);
          break;
        case 'Manager':
          this.router.navigate(['/main/dashboard']);
          break;
        case 'Ranger':
          this.router.navigate(['/ranger']);
          break;
        case 'Veterinarian':
          this.router.navigate(['/veterinarian']);
          break;
        case 'Biologist':
          this.router.navigate(['/biologist']);
          break;
        case 'Conservationist':
          this.router.navigate(['/conservationist']);
          break;
        default:
          this.router.navigate(['/login']); 
         
          break;
      }
    
  }
}
