import { Routes } from '@angular/router';
import { LoginComponent } from './components/login/login.component';
import { UserFormComponent } from './components/user-form/user-form.component';
import { AddSanctuaryComponent } from './components/add-sanctuary/add-sanctuary.component';
import { SanctuaryListComponent } from './components/sanctuary-list/sanctuary-list.component';
import { IncidentComponent } from './components/incident/incident.component';
import { IncidentFormComponent } from './components/incident-form/incident-form.component';
import { AnimalComponent } from './components/animal/animal.component';
import { RangerDashboardComponent } from './components/ranger-dashboard/ranger-dashboard.component';
import { VetFormComponent } from './components/vet-form/vet-form.component';
import { VetDashboardComponent } from './components/vet-dashboard/vet-dashboard.component';
import { CostFormComponent } from './components/cost-form/cost-form.component';
import { MainDashboardComponent } from './components/main-dashboard/main-dashboard.component';
import { ProjectFormComponent } from './components/project-form/project-form.component';
import { ReportComponent } from './components/report/report.component';
import { AdminComponent } from './components/admin/admin.component';
import { AnimalsListComponent } from './components/animals-list/animals-list.component';
import { UsersListComponent } from './components/users-list/users-list.component';
import { ProjectsComponent } from './components/projects/projects.component';
import { ReportListComponent } from './components/report-list/report-list.component';
import { ExpensesListComponent } from './components/expenses-list/expenses-list.component';
import { WildlifeComponent } from './components/wildlife/wildlife.component';
import { EnvironmentalDataComponent } from './components/environmental-form/environmental-form.component';
import { BiologistDashboardComponent } from './components/biologist-dashboard/biologist-dashboard.component';
import { ConservationistComponent } from './components/conservationist/conservationist.component';
import { AuthGuard } from './auth.guard';
import { AutogeneratedReportComponent } from './components/autogenerated-report/autogenerated-report.component';
import { WildlifeListComponent } from './components/wildlife-list/wildlife-list.component';
import { HomeComponent } from './components/home/home.component';

export const routes: Routes = [

  {
    path: 'main',
    component: AdminComponent,
    children: [
      { path: 'dashboard', component: MainDashboardComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'sanctuaries', component: SanctuaryListComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'animals', component: AnimalsListComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'incidents', component: IncidentComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'users', component: UsersListComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'projects', component: ProjectsComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'reports', component: ReportListComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'expenses', component: ExpensesListComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
      { path: 'wildlife', component: WildlifeListComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] }},
      { path: 'assessments', component: ConservationistComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager']} },
    ]
  },

  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: "user/add", component: UserFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'sanctuaries', component: SanctuaryListComponent },
  { path: "sanctuary/add", component: AddSanctuaryComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'sanctuaries/edit/:id', component: AddSanctuaryComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'incident/add', component: IncidentFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Ranger', 'Manager'] } },
  { path: 'incident/edit/:id', component: IncidentFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Ranger', 'Manager'] } },
  { path: 'animal/add', component: AnimalComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Biologist', 'Manager'] } },
  { path: 'animal/edit/:id', component: AnimalComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Biologist', 'Manager'] } },
  { path: 'ranger', component: RangerDashboardComponent, canActivate: [AuthGuard], data: { roles: ['Ranger', 'Manager'] } },
  { path: 'MedicalRecord/add', component: VetFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Veterinarian', 'Manager'] } },
  { path: 'MedicalRecord/edit/:id', component: VetFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Veterinarian', 'Manager'] } },
  { path: 'veterinarian', component: VetDashboardComponent, canActivate: [AuthGuard], data: { roles: ['Veterinarian', 'Manager'] } },
  { path: 'expense/add', component: CostFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'expense/edit/:id', component: CostFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'main', component: MainDashboardComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'animals', component: AnimalsListComponent },
  { path: 'incidents', component: IncidentComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Ranger', 'Conservationist', 'Manager'] } },
  { path: 'project/add', component: ProjectFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'report/add', component: ReportComponent },
  { path: 'project/edit/:id', component: ProjectFormComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Manager'] } },
  { path: 'report/edit/:id', component: ReportComponent },
  { path: 'wildlife/add', component: WildlifeComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Biologist', 'Manager'] } },
  { path: 'wildlife/edit/:id', component: WildlifeComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Biologist', 'Manager'] } },
  { path: 'assessment/add', component: EnvironmentalDataComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Conservationist', 'Manager'] } },
  { path: 'assessment/edit/:id', component: EnvironmentalDataComponent, canActivate: [AuthGuard], data: { roles: ['Admin', 'Conservationist', 'Manager'] } },
  { path: 'biologist', component: BiologistDashboardComponent, canActivate: [AuthGuard], data: { roles: ['Biologist', 'Manager'] } },
  { path: 'conservationist', component: ConservationistComponent, canActivate: [AuthGuard], data: { roles: ['Conservationist', 'Manager'] } },
  { path: 'report/generated', component: AutogeneratedReportComponent },
  { path: 'home', component: HomeComponent }

];

/*
export const routes: Routes = [
  {
    path: 'main',
    component: AdminComponent,
    children: [
      { path: 'dashboard', component: MainDashboardComponent },
      { path: 'sanctuaries', component: SanctuaryListComponent },
      { path: 'animals', component: AnimalsListComponent },
      { path: 'incidents', component: IncidentComponent },
      { path: 'users', component: UsersListComponent },
      { path: 'projects', component: ProjectsComponent },
      { path: 'reports', component: ReportListComponent },
      { path: 'expenses', component: ExpensesListComponent },
      {path:'wildlife',component:WildlifeListComponent},
      {path:'assessments',component:ConservationistComponent},
    ]
  },
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: "user/add", component: UserFormComponent },
  { path: 'sanctuaries', component: SanctuaryListComponent },
  { path: "sanctuary/add", component: AddSanctuaryComponent },
  { path: 'sanctuary/edit/:id', component: AddSanctuaryComponent },
  { path: 'incident/add', component: IncidentFormComponent },
  { path: 'incident/edit/:id', component: IncidentFormComponent },
  { path: 'animal/add', component: AnimalComponent },
  { path: 'animal/edit/:id', component: AnimalComponent },
  { path: 'ranger', component: RangerDashboardComponent },
  { path: 'MedicalRecord/add', component: VetFormComponent },
  { path: 'MedicalRecord/edit/:id', component: VetFormComponent },
  { path: 'veterinarian', component: VetDashboardComponent },
  { path: 'expense/add', component: CostFormComponent },
  { path: 'expense/edit/:id', component: CostFormComponent },
  { path: 'main', component: MainDashboardComponent },
  { path: 'animals', component: AnimalsListComponent },
  { path: 'incidents', component: IncidentComponent },
  { path: 'project/add', component: ProjectFormComponent },
  { path: 'report/add', component: ReportComponent },
  { path: 'project/edit/:id', component: ProjectFormComponent },
  { path: 'report/edit/:id', component: ReportComponent },
  { path: 'wildlife/add', component: WildlifeComponent },
  { path: 'wildlife/edit/:id', component: WildlifeComponent },
  { path: 'assessment/add', component: EnvironmentalDataComponent },
  { path: 'assessment/edit/:id', component: EnvironmentalDataComponent },
  { path: 'biologist', component: BiologistDashboardComponent },
  { path: 'conservationist', component: ConservationistComponent },
  {path:'report/generated',component:AutogeneratedReportComponent},
  {path:'home',component:HomeComponent}
];*/
